# Generated by Django 5.2.6 on 2025-09-21 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_apps', '0002_module_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='url_path',
            field=models.CharField(help_text='Url path sudah digunakan, harus unik. hanya huruf kecil, angka, hyphens (-), dan slashes (/) yang diperbolehkan.', max_length=255, unique=True),
        ),
    ]
