# Generated by Django 5.2.6 on 2025-09-21 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_apps', '0003_alter_module_url_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='url_path',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
