# Generated by Django 5.2.6 on 2025-09-21 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_apps', '0005_namaproduct'),
    ]

    operations = [
        migrations.AlterField(
            model_name='namaproduct',
            name='barcode',
            field=models.TextField(unique=True),
        ),
    ]
