# Generated by Django 5.2.6 on 2025-09-21 12:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_apps', '0006_alter_namaproduct_barcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='namaproduct',
            name='extra_fields',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='namaproduct',
            name='barcode',
            field=models.TextField(blank=True, unique=True),
        ),
        migrations.AlterField(
            model_name='namaproduct',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.CreateModel(
            name='ProductAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100)),
                ('value', models.TextField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attributes', to='main_apps.namaproduct')),
            ],
        ),
    ]
