# Generated by Django 5.2.6 on 2025-09-21 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_apps', '0007_namaproduct_extra_fields_alter_namaproduct_barcode_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='namaproduct',
            name='extra_fields',
        ),
        migrations.DeleteModel(
            name='ProductAttribute',
        ),
    ]
